# Generated by Django 2.2.2 on 2019-06-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('hit', models.IntegerField()),
                ('reg_date', models.DateTimeField(auto_now=True)),
                ('group_no', models.IntegerField()),
                ('order_no', models.IntegerField()),
                ('depth', models.IntegerField()),
            ],
        ),
    ]
